# Model Configuration
debug:
  enabled: true  # Set to false for full training
  train_samples: 20
  val_samples: 10
  # test_samples: 5
  test_fraction: 0.05
  batch_size: 5
  num_epochs: 10

model:
  max_length: 512
  max_source_length: 256 #################
  checkpoint_dir: "models/checkpoints"
  best_checkpoint: "models/checkpoints/best_model.pt"
  name: "Salesforce/codet5-base"

# Data Configuration
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  train_path: "data/processed/train_tokenized.pt"
  val_path: "data/processed/validation_tokenized.pt"
  test_path: "data/processed/test_tokenized.pt"
  
# Training Configuration
training:
  batch_size: 32
  learning_rate: 2e-5
  num_epochs: 10
  warmup_steps: 1000
  gradient_accumulation_steps: 2
  max_grad_norm: 1.0
  weight_decay: 0.01
  early_stopping_patience: 3
  gradient_clip_val: 1.0

# Evaluation Configuration
evaluation:
  batch_size: 64
  beam_size: 4

# Logging Configuration
logging:
  level: "INFO"
  file: "training.log"
  tensorboard_dir: "runs"
  log_every_n_steps: 100
